### PR TITLE
Fix null redirect

### LINKED ISSUE #16: [BUG] Object of class redirect could not be converted to string.
I'm using Auth v3.0.1 on top of bolt 3.3.3.

-----------

Error on using the urls described here: https://boltauth.com/routes-urls.html

Details
-------

 - Relevant Bolt Auth Version: 3.0.1
 - Relevant Bolt Version: 3.3.3
 - PHP version: PHP 7.0.22-0ubuntu0.16.04.1

Reproduction
------------

I just migrated from a simple 2.2 install to 3.3. I wasnt using boltauth but I want to. But the links wont work. The twig functions like {{ auth_auth_login() }} do work.

When visiting /auth/profile/register or /authentication/reset i got:

`ContextErrorException in Bag.php line 276:
Catchable Fatal Error: Object of class Bolt\Extension\BoltAuth\Auth\AccessControl\Redirect could not be converted to string
in Bag.php line 276
at ErrorHandler->handleError('4096', 'Object of class Bolt\Extension\BoltAuth\Auth\AccessControl\Redirect could not be converted to string', '/home/elimkerk/web/vendor/bolt/collection/src/Bag.php', '276', array('separator' => ' '))
at implode(' ', array(object(Redirect))) in Bag.php line 276
at Bag->join(' ') in RequestSanitiser.php line 49`

### PR DESCRIPTION
**Pull request by artggd**
This fixes #16 by making sure the redirect after login is not null.

### CODE REVIEW

**Comment by SvanteRichter** [comment]
Sorry it's taken me a while, this looks good, thanks!

**Comment by ncareau** [comment]
@SahAssar Hey, thanks for merging, but can you produce a release soon with at least this fix ? Thanks.

**Comment by SvanteRichter** [comment]
@ncareau This is in v3.0.3, I'll tag a release with ed709e5, which I think is the one you are looking for.

**Comment by ncareau** [comment]
Yeah you're right, this is not what i needed. But it works now with the new release. Thank you very much.

**Pull request merged**
